name: Weekly Python Script Runner

on:
  # 手动触发
  workflow_dispatch:
  # 北京时间每周五凌晨3点触发（UTC时间前一天的19:00）
  schedule:
    - cron: '0 19 * * 4'  # UTC时间周四19:00 = 北京时间周五03:00

env:
  API_KEY: ${{ secrets.API_KEY }}  # 从仓库Secret读取

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 指定您需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有requirements.txt
        # 或者直接安装特定包

    - name: Run Python script
      run: |
        python main.py  # 替换为您的脚本名称

    - name: Collect TXT files
      run: |
        # 创建收集目录
        mkdir -p collected_files
        # 复制所有txt文件（包括子目录）
        cp *.md collected_files/
        cp *.pdf collected_files/
        cp *.txt collected_files/
        # 显示收集结果
        ls -l collected_files/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: text-files
        path: collected_files/
        if-no-files-found: warn