name: Run ArxivAutoJob Pipeline

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use latest Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}" >> $GITHUB_ENV
        echo "OPENAI_MODEL=${{ secrets.MODEL_NAME }}" >> $GITHUB_ENV # Corrected to MODEL_NAME as per common practice
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      # Ensure these secrets are configured in your GitHub repository settings

    - name: Run ArxivAutoJob
      run: python main.py

    - name: Deploy RSS and Summary to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' # Only deploy from main branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./download # Directory containing rss.xml and summary.md
        keep_files: true # Keep existing files in gh-pages branch, only update changed ones
        commit_message: "Update ArxivAutoJob RSS and Summary [skip ci]"
